app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//Route::get('logueo', 'autenticacionController@index');
Route::group(['middleware' => 'auth'], function () {

Route::get('/', 'principalController@index');
Route::resource('roles', 'rolesController');
Route::get('niveles/ajxniveles', 'nivelesController@listado');
Route::resource('niveles', 'nivelesController');
Route::resource('planes', 'planesController');
Route::resource('jornadas', 'jornadasController');
Route::resource('puestos', 'puestosController');
Route::resource('secciones', 'seccionesController');
Route::resource('grados', 'gradosController');
Route::get('asignarniveles/obtenerajx', 'planesnivelesController@bscajx');
Route::resource('asignarniveles', 'planesnivelesController');
Route::resource('salones', 'salonesController');
Route::resource('areas/autocomplete', 'areasController@areas');
Route::resource('areas', 'areasController');
Route::get('personas/autocomplete', 'personasController@bscautomplete');
Route::get('usuarios/autocomplete2', 'personasController@buscausuario');//busqueda de usuarios
Route::get('personas/autocomplete/docente/', 'personasController@buscadocente');
Route::resource('personas', 'personasController');
Route::resource('carreras', 'carrerasController');
Route::resource('gradoniveles', 'gradosnivelesController');
Route::resource('pensum/pensumgrado', 'asignacionareasController@pensumGrado');
Route::resource('pensum/grados', 'asignacionareasController@grados');
Route::resource('pensum', 'asignacionareasController');
Route::resource('subopciones', 'subopcionesController');
Route::resource('permisosroles', 'permisosrolesController');
Route::resource('usuarios', 'usuariosController');
Route::resource('prueba', 'pruebaController');
Route::resource('asignaciondocente/grados', 'asignaciondocenteController@getGrados');
Route::resource('asignaciondocente', 'asignaciondocenteController');
Route::get('inscripcionestudiantes/constancia', 'inscripcionController@constancia');
Route::resource('inscripcionestudiantes', 'inscripcionController');
Route::resource('municipios', 'municipioController');
Route::resource('unidades', 'unidadesController');
Route::resource('foros', 'forosController');
Route::resource('respuestasforos', 'respuestasforosController');

//cambios hechos por jose florian
Route::resource('verestudiantes', 'EstudianteController');//cj
Route::resource('verusuario', 'UsuariosRolesController');//cj
//actividades y tareas
Route::resource('Actividad', 'ActividadesController');//cj
Route::resource('misactividades',  'misActividadesController');//cj
Route::resource('respuestaactividades', 'RespondeActividadController');//cj
Route::resource('misrespuestasactividades', 'MisRespuestasActividadController');//cj
Route::resource('Nota', 'NotaController');//cj
Route::resource('MisNotas', 'MisNotasController');//cj
Route::resource('MisNotasPorUnidad', 'MisNotasPorUnidadController');//cj
Route::resource('horarios', 'horarioController');//cj
//inscripcion pdf 
Route::get('report', 'PdfController@invoice');
Route::get('personas/autocomplete/usuario/', 'personasController@buscausuario');
Route::get('asignarareas/obtenerajx', 'horarioController@bscajx');//cj horarios
//opciones de estudiantes
Route::resource('estudiantes', 'miscursosController');
Route::resource('misforos', 'misforosController');
Route::resource('todasmisactividades', 'todasMisActividadesController');
Route::resource('MisNotasTotales', 'MisNotasTotalesController');
Route::resource('mishorarios', 'mishorariosController');
// subir archivos
Route::get('file','tareaController@index');
Route::post('file/store','tareaController@store');
Route::get('file/show','tareaController@showall');
Route::get('file/show/{id}','tareaController@show');
Route::get('file/user/download', 'tareaController@download');


//opciones de profesores
Route::resource('docente', 'docenteController');
Route::resource('misforosdocente', 'misforosdocenteController');
Route::resource('misactividadesdocente', 'misactividadesdocenteController');
Route::resource('mishorariosdocente', 'mishorariosdocenteController');
Route::resource('misnotashijos', 'misnotashijosController');
Route::resource('misnotascursohijos', 'misnotascursohijosController');


//opciones de padres de familia
Route::resource('misalumnos', 'padresalumnosController');
Route::resource('misdocnetes', 'padresdocenteController');
Route::resource('tutores', 'TutoresController');
Route::resource('tutoreshijos', 'TutoresController');
Route::resource('misnotashijos', 'misnotashijosController');
Route::resource('miscursosprofesores', 'miscursosprofesoresController');
Route::resource('misactividadeshijos', 'actividadesdehijosController');


//mis opciones de configuracion
Route::resource('miperfil', 'miperfilController');//personaliza imagen y datos de usuario
Route::resource('misconfiguraciones', 'misconfiguracionesController');//personaliza imagen y nombres de institucion
Route::resource('helpdesk', 'helpdeskController');//panel de ayuda y soporte documentacion y foros de ayuda
Route::resource('enviomensajes', 'enviomensajesController');//formulario de contacto y ayuda

//NOTIFICACIONES
Route::resource('notificaciones', 'notificacionesController');//formulario para envio de notificaciones
Route::resource('notificaciones/autocomplete/', 'notificacionesController@notificaciones');

Route::resource('plantillas.menu', 'menunotificacionesController');//esta babosada no sirve por las rutas verificar si se puede hacer con js

Route::resource('notificacionesdocente', 'MisNotificacionesDocenteController');
Route::resource('notificacionesalumno', 'MisNotificacionesAlumnoController');
Route::resource('notificacionespadre', 'MisNotificacionesPadreController');
Route::resource('notificacionesuser', 'MisNotificacionesPadreController');//pendiente

//calendario de hoy

Route::resource('indexalumno', 'miHorarioHoyController');

//director

Route::resource('administra_notas_niveles', 'DirectorController');
Route::resource('buscarnotas', 'BuscarNotasController');
Route::resource('buscarnotasbimestre', 'BuscarNotasBimiestreController');
Route::resource('resultadosbuscarnotasbimestre', 'resultadosbuscarnotabirmestreController');










//Route::get('constancia', 'reportesController@constancia_inscripcion');
//Route::get('pagos', 'reportesController@constancia_inscripcion');
});//fin del rout group
/*Route::get('/', function () {
    return view('welcome');
});*/

Route::auth();

//Route::get('/home', 'HomeController@index');

app/Http/Controllers/planesController.php
<?php

namespace education\Http\Controllers;

use Illuminate\Http\Request;

use education\Http\Requests;
use education\Http\Controllers\menuController;
use education\Planes;
use \Validator;
use Session;
use education\User;
use Auth;
class planesController extends Controller
{
    protected $menu;
    public function __construct()
    {
      $m = new menuController();
      $this->menu = $m->index();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::where('id', Auth::user()->id)->first();
        if ($user->can(['crear-plan', 'editar-plan', 'estado-plan'])) {
          $planes = Planes::All();
          return view('planes.index', ['planes'=>$planes, 'items'=>$this->menu]);
        }
        return abort(403);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = User::where('id', Auth::user()->id)->first();
        if ($user->can('crear-plan')) {
          return view('planes.nplan', ['items'=>$this->menu]);
        }
        return abort(403);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      //crear el arreglo de los mensajes de validacion
          $mensajes = array(
          'required' => 'Hey! EL campo :attribute es requerido!!!.',
          'min' => 'Hey! El campo :attribute debe tener como minimo :min caracteres!!!',
          'max' => 'Hey! El campo :attribute no puede tener mas de :max caracteres!!!',
          'unique' => 'Hey! El valor del campo :attribute ya existe en la base de datos, tiene que ser unico!!!',
          );

          $v = Validator::make(
          $request->all(),
           [
                'nombre_plan' => 'required|min:4|max:25|unique:PLANES,nombre_plan',
            ],
            $mensajes);

        if ($v->fails())
        {
            return redirect()->back()->withInput()->withErrors($v->errors());
        }
      $nombre = $request['nombre_plan'];
      //$client->create($request->all());
      //$clients = Client::all();
      //return \View::make('list', compact('clients'));
      $result = Planes::setPlanes($nombre);
      Session::flash('mensaje', $result[0]->msg);
      return redirect('/planes');
      //return $this->index();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::where('id', Auth::user()->id)->first();
        if ($user->can('editar-plan')) {
          $plan = Planes::findPlan($id);
          return view('planes.eplan', ['plan'=>$plan, 'items'=>$this->menu]);
        }
        return abort(403);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      //crear el arreglo de los mensajes de validacion
          $mensajes = array(
          'required' => 'Hey! EL campo :attribute es requerido!!!.',
          'min' => 'Hey! El campo :attribute debe tener como minimo :min caracteres!!!',
          'max' => 'Hey! El campo :attribute no puede tener mas de :max caracteres!!!',
          'unique' => 'Hey! El valor del campo :attribute ya existe en la base de datos, tiene que ser unico!!!',
          );

          $v = Validator::make(
          $request->all(),
           [
                'nombre_plan' => 'required|min:4|max:25|unique:PLANES,nombre_plan,'.$id.',id_plan',
            ],
            $mensajes);

        if ($v->fails())
        {
            return redirect()->back()->withInput()->withErrors($v->errors());
        }
      $nombre = $request['nombre_plan'];
      $result = Planes::updatePlan($id, $nombre);
      Session::flash('mensaje', $result[0]->msg);
      return redirect('/planes');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, Request $request)
    {
      $estado = $request['estado'];
      if ($estado == 1) {
        Planes::statePlan($id, false);//se cambia el estado a desactivado
      } else {
        Planes::statePlan($id, true);//se camia el estado a activado
      }
      $planes = Planes::All();
      return response()->json($planes);
    }
}

app/Http/Controllers/puestosController.php
<?php

namespace education\Http\Controllers;

use Illuminate\Http\Request;

use education\Http\Requests;
use education\Http\Controllers\menuController;
use education\Puestos;
use \Validator;
use Session;
use education\User;
use Auth;
class puestosController extends Controller
{
    protected $menu;
    public function __construct()
    {
      $m = new menuController();
      $this->menu = $m->index();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::where('id', Auth::user()->id)->first();
        if ($user->can(['crear-puesto', 'editar-puesto', 'estado-puesto'])) {
          $puestos = Puestos::All();
          return view('puestos.index', ['puestos'=>$puestos, 'items'=>$this->menu]);
        }
        return abort(403);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = User::where('id', Auth::user()->id)->first();
        if ($user->can('crear-puesto')) {
          return view('puestos.npuesto', ['items'=>$this->menu]);
        }
        return abort(403);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      //crear el arreglo de los mensajes de validacion
          $mensajes = array(
          'required' => 'Hey! EL campo :attribute es requerido!!!.',
          'min' => 'Hey! El campo :attribute debe tener como minimo :min caracteres!!!',
          'max' => 'Hey! El campo :attribute no puede tener mas de :max caracteres!!!',
          'unique' => 'Hey! El valor del campo :attribute ya existe en la base de datos, tiene que ser unico!!!',
          );

          $v = Validator::make(
          $request->all(),
           [
                'nombre_puesto' => 'required|min:4|max:30|unique:PUESTOS,nombre_puesto',
            ],
            $mensajes);

        if ($v->fails())
        {
            return redirect()->back()->withInput()->withErrors($v->errors());
        }
      $nombre = $request['nombre_puesto'];
      $result = Puestos::setPuesto($nombre);
      Session::flash('mensaje', $result[0]->msg);
      return redirect('/puestos');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::where('id', Auth::user()->id)->first();
        if ($user->can('editar-puesto')) {
          $puesto = Puestos::findPuesto($id);
          return view('puestos.epuesto',['puesto'=>$puesto, 'items'=>$this->menu]);
        }
        return abort(403);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      //crear el arreglo de los mensajes de validacion
          $mensajes = array(
          'required' => 'Hey! EL campo :attribute es requerido!!!.',
          'min' => 'Hey! El campo :attribute debe tener como minimo :min caracteres!!!',
          'max' => 'Hey! El campo :attribute no puede tener mas de :max caracteres!!!',
          'unique' => 'Hey! El valor del campo :attribute ya existe en la base de datos, tiene que ser unico!!!',
          );

          $v = Validator::make(
          $request->all(),
           [
                'nombre_puesto' => 'required|min:4|max:30|unique:PUESTOS,nombre_puesto,'.$id.',id_puesto',
            ],
            $mensajes);

        if ($v->fails())
        {
            return redirect()->back()->withInput()->withErrors($v->errors());
        }
      $nombre = $request['nombre_puesto'];
      $result = Puestos::updatePuesto($id, $nombre);
      Session::flash('mensaje', $result[0]->msg);
      return redirect('/puestos');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, Request $request)
    {
        $estado = $request['estado'];
        if ($estado == 1) {
          Puestos::statePuesto($id, FALSE);
        } else {
          Puestos::statePuesto($id, TRUE);
        }
        $puestos = Puestos::All();
        return response()->json($puestos);
    }
}

resources/views/puestos/planes/eplan.blade.php
@extends('principal')

@section('titulo')
  <title>Editar Plan</title>
@endsection

@section('cuerpo')
  <div id="page-wrapper">
    <div class="row">
      <div class="col-sm-12">
        <h1 class="page-header text-center">Editar Plan</h1>
        <!-- Errores del formulario del lado del servidor -->
        @include('mensajes.errores')
      </div>
      <div class="col-sm-12">
        {!!Form::model($plan, ['route'=>['planes.update', $plan->id_plan], 'method'=>'PUT', 'class'=>'form-horizontal', 'id'=>'nplan'])!!}
        <!-- Campos del formuario-->
        @include('planes.form.campos')
        {!!Form::close()!!}
      </div>
    </div>
  </div>
@endsection

resources/views/puestos/planes/index.blade.php
@extends('principal')

@section('titulo')
  <title>Planes</title>
@endsection

@section('cuerpo')
  <div id="page-wrapper">
    <div class="row">
      <div class="col-sm-12">
        <h1 class="page-header text-center">Planes</h1>
          @include('mensajes.msg')
      </div>
      <div class="col-sm-12">
        @permission('crear-plan')
        {!!link_to_route('planes.create', $title ='Nuevo Plan', $parameters = null, $attributes = ['class'=>'btn btn-primary'])!!}
        <br>
        <br>
        @endpermission
        @if (count($planes) == 0)
          <p class="text-info">
            No se han registrado planes aun...
          </p>
        @else
          <table class="table table-hover table-bordered">
            <thead>
              <tr>
                <th>
                  NO
                </th>
                <th>
                  NOMBRE PLAN
                </th>
                @permission('editar-plan')
                <th>
                  ACTUALIZAR
                </th>
                @endpermission
                @permission('estado-plan')
                <th>
                  ESTADO
                </th>
                @endpermission
              </tr>
            </thead>
            <tbody id="datosPlanes">
              @foreach($planes as $key => $plan)
                <tr>
                  <td>
                    {{ $key+1 }}
                  </td>
                  <td>
                    {{ mb_strtoupper($plan->nombre_plan) }}
                  </td>
                  @permission('editar-plan')
                  <td>
                    {!!link_to_route('planes.edit', $title = 'Editar', $parameters = $plan->id_plan, $attributes = ['class'=>'btn btn-primary'])!!}
                  </td>
                  @endpermission
                  @permission('estado-plan')
                  <td>
                    @if($plan->estado_plan == true)
                      {!!link_to_route('planes.destroy', $title = 'Habilitado', $parameters = null, $attributes = ['class'=>'btn btn-success eliminarPlan', 'data-id'=>$plan->id_plan, 'data-estado'=>$plan->estado_plan])!!}
                    @else
                      {!!link_to_route('planes.destroy', $title = 'Deshabilitado', $parameters = null, $attributes = ['class'=>'btn btn-danger eliminarPlan', 'data-id'=>$plan->id_plan, 'data-estado'=>$plan->estado_plan])!!}
                    @endif
                  </td>
                  @endpermission
                </tr>
              @endforeach
            </tbody>
          </table>
          <input type="hidden" name="_token" value="{{ csrf_token() }}" id="token">
        @endif
      </div>
    </div>

    <!-- Mensaje de carga-->
    @include('mensajes.carga')

  </div>



@endsection

resources/views/puestos/planes/nplan.blade.php
@extends('principal')

@section('titulo')
  <title>Nuevo Plan</title>
@endsection

@section('cuerpo')
  <div id="page-wrapper">
    <div class="row">
      <div class="col-sm-12">
        <h1 class="page-header text-center">Nuevo Plan</h1>
        @include('mensajes.errores')
      </div>
      <div class="col-sm-12">
        {!!Form::open(['route'=>'planes.store', 'method'=>'POST', 'class'=>'form-horizontal', 'id'=>'nplan'])!!}
          @include('planes.form.campos')
        {!!Form::close()!!}
      </div>
    </div>
  </div>
@endsection

resources/views/puestos/planes/search.blade.php
{!! Form::open(array('url'=>'areas','method'=>'GET','autocomplete'=>'off','role'=>'search')) !!}
<div class="form-group">
<br/>
  <div class="input-group">
    
    <input type="text" class="form-control" name="searchText" placeholder="Buscar cursos por nombre..." value="{{$searchText}}">

    <span class="input-group-btn"> <div class="" aria-hidden="true"></div>

    <button type="submit" class="btn btn-info"><div class="fa fa-search"></div>Buscar</button>
    </span>
  </div>
</div>

{{Form::close()}}